version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - cp package.json dist/
      - cp -R node_modules dist/
artifacts:
  files:
    - '**/*'
  base-directory: dist
