version: 0.2

phases:
  install:
    commands:
      - npm install

  pre_build:
    commands:
      - cd src/
      - mkdir -p ./config/firestore
      - aws s3 cp s3://firestoreconfig/secret.json ./config/firestore/secret.json
      - cd ..

  build:
    commands:
      - npm run build
      - ls -l
      - ls -a
      - ls dist/

artifacts:
  files:
    - 'dist/**/*'
    - 'package.json'
    - 'Procfile'
    - 'node_modules/**/*'
