version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - pwd
      - ls
      - mkdir -p src/config/firestore
      - aws s3 cp s3://firestoreconfig/secret.json src/config/firestore/config.json
      - ls -a
      - ls src/config/firestore
      - cat src/config/firestore/config.json
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
