version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - mkdir -p src/config/firestore
      - aws s3 cp https://firestoreconfig.s3.eu-north-1.amazonaws.com/secret.json src/config/firestore/config.json
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
