version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - mkdir -p config/firestore
      - touch config/firestore/config.json
      - echo $FIREBASE_CONFIG > config/firestore/config.json
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
