version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - mkdir -p var/app/current/src/config/firestore
      - aws s3 cp s3://firestoreconfig/secret.json src/config/firestore/config.json
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
