version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - pwd
      - ls -a
      - mkdir -p /codebuild/output/src2910707537/src/src/config/firestore
      - aws s3 cp s3://firestoreconfig/secret.json /codebuild/output/src2910707537/src/src/config/firestore/config.json
      - cat /codebuild/output/src2910707537/src/src/config/firestore/config.json
      - tree /codebuild/output/src2910707537/src

  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
