name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
        env:
          FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY_ID: ${{ vars.FIREBASE_PRIVATE_KEY_ID }}
          FIREBASE_PRIVATE_KEY: ${{ vars.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ vars.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_CLIENT_ID: ${{ vars.FIREBASE_CLIENT_ID }}
          FIREBASE_AUTH_URI: ${{ vars.FIREBASE_AUTH_URI }}
          FIREBASE_TOKEN_URI: ${{ vars.FIREBASE_TOKEN_URI }}
          FIREBASE_AUTH_CERT_URL: ${{ vars.FIREBASE_AUTH_CERT_URL }}
          FIREBASE_CLIENT_CERT_URL: ${{ vars.FIREBASE_CLIENT_CERT_URL }}
          JWT_SECRET: ${{ vars.JWT_SECRET }}
          MAIL_HOST: ${{ vars.MAIL_HOST }}
          MAIL_PORT: ${{ vars.MAIL_PORT }}
          MAIL_USER: ${{ vars.MAIL_USER }}
